// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.FortuneCookieGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("requested_type")]
        public string RequestedType { get; set; }

        [JsonProperty("fortunes")]
        public Fortune[] Fortunes { get; set; }

        [JsonProperty("available_types")]
        public string[] AvailableTypes { get; set; }
    }

    public partial class Fortune
    {
        [JsonProperty("fortune")]
        public string FortuneFortune { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("lucky_numbers")]
        public long[] LuckyNumbers { get; set; }
    }
}
